name: CustomItemManager
main: io.github.silicondev.customitemmanager.CustomItemManager
version: 0.0.5-SNAPSHOT
author: silicondev
permissions:
  customitemmanager.*:
    default: false
    description: "Gives permission to all commands."
    children:
      customitemmanager.test: true
      customitemmanager.help: true
  customitemmanager.test:
    description: "Tests the plugin."
    default: true
  customitemmanager.help:
    description: "Displays the help text."
    default: true
  customitemmanager.item:
    description: "Base command for item management."
    default: true
  customitemmanager.item.set:
    description: "Saves a custom item to the database."
    default: true
  customitemmanager.item.spawn:
    description: "Spawns a custom item from the database."
    default: true
  customitemmanager.item.delete:
    description: "Deletes a custom item from the database."
    default: true
  customitemmanager.item.list:
    description: "Lists all custom items in the database."
    default: true
commands:
  customitem:
    description: "Tests the plugin."
    usage: "/customitem help"
    aliases: [customitem, ci]