name: CustomItemManager
main: io.github.silicondev.customitemmanager.CustomItemManager
version: 0.0.2-SNAPSHOT
author: silicondev
permissions:
  customitemmanager.*:
    default: false
    description: "Gives permission to all commands."
    children:
      customitemmanager.test: true
      customitemmanager.help: true
  customitemmanager.test:
    default: true
  customitemmanager.help:
    description: "Displays help message."
    default: true
commands:
  customitem:
    description: "Tests the plugin."
    usage: "/customitem help"
    aliases: [customitem, ci]