name: CustomItemManager
main: io.github.silicondev.customitemmanager.CustomItemManager
version: 0.2.0-SNAPSHOT
author: silicondev
permissions:
  customitemmanager.*:
    default: op
    description: "Gives permission to all commands."
    children:
      customitemmanager.test: true
      customitemmanager.help: true
      customitemmanager.save: true
      customitemmanager.item: true
      customitemmanager.item.set: true
      customitemmanager.item.spawn: true
      customitemmanager.item.delete: true
      customitemmanager.item.list: true
      customitemmanager.command.add: true
      customitemmanager.command.remove: true
      customitemmanager.command.clear: true
      customitemmanager.command.list: true
  customitemmanager.item.*:
    default: false
    description: "Gives permission to all item based commands."
    children:
      customitemmanager.item: true
      customitemmanager.item.set: true
      customitemmanager.item.spawn: true
      customitemmanager.item.delete: true
      customitemmanager.item.list: true
  customitemmanager.*:
    default: false
    description: "Gives permission to all command based commands."
    children:
      customitemmanager.command.add: true
      customitemmanager.command.remove: true
      customitemmanager.command.clear: true
      customitemmanager.command.list: true
  customitemmanager.test:
    description: "Tests the plugin."
    default: op
  customitemmanager.help:
    description: "Displays the help text."
    default: op
  customitemmanager.save:
    description: "Saves all data to configs."
    default: op
  customitemmanager.item:
    description: "Base command for item management."
    default: op
  customitemmanager.item.set:
    description: "Saves a custom item to the database."
    default: op
  customitemmanager.item.spawn:
    description: "Spawns a custom item from the database."
    default: op
  customitemmanager.item.delete:
    description: "Deletes a custom item from the database."
    default: op
  customitemmanager.item.list:
    description: "Lists all custom items in the database."
    default: op
  customitemmanager.command.add:
    description: "Adds a runnable command to the item."
    default: op
  customitemmanager.command.remove:
    description: "Removes a command from the item."
    default: op
  customitemmanager.command.clear:
    description: "Clears all commands from the item."
    default: op
  customitemmanager.command.list:
    description: "Lists all commands from the item."
    default: op
commands:
  customitem:
    description: "Tests the plugin."
    usage: "/customitem help"
    aliases: [customitem, ci]