name: CustomItemManager
main: io.github.silicondev.customitemmanager.CustomItemManager
version: 0.2.6-SNAPSHOT
author: silicondev
permissions:
  customitemmanager.*:
    default: op
    description: "Gives permission to all commands."
    children:
      customitemmanager.test: true
      customitemmanager.help: true
      customitemmanager.save: true
      customitemmanager.spawn: true
      customitemmanager.delete: true
      customitemmanager.list: true
      customitemmanager.command.add: true
      customitemmanager.command.remove: true
      customitemmanager.command.clear: true
      customitemmanager.command.list: true
      customitemmanager.reload: true
  customitemmanager.command.*:
    default: op
    description: "Gives permission to all command based commands."
    children:
      customitemmanager.command.add: true
      customitemmanager.command.remove: true
      customitemmanager.command.clear: true
      customitemmanager.command.list: true
  customitemmanager.test:
    description: "Tests the plugin."
    default: op
  customitemmanager.help:
    description: "Displays the help text."
    default: op
  customitemmanager.save:
    description: "Saves a custom item to the database."
    default: op
  customitemmanager.spawn:
    description: "Spawns a custom item from the database."
    default: op
  customitemmanager.delete:
    description: "Deletes a custom item from the database."
    default: op
  customitemmanager.list:
    description: "Lists all custom items in the database."
    default: op
  customitemmanager.command.add:
    description: "Adds a runnable command to the item."
    default: op
  customitemmanager.command.remove:
    description: "Removes a command from the item."
    default: op
  customitemmanager.command.clear:
    description: "Clears all commands from the item."
    default: op
  customitemmanager.command.list:
    description: "Lists all commands from the item."
    default: op
  customitemmanager.reload:
    description: "Reloads the plugin's configuration files."
commands:
  customitem:
    description: "Tests the plugin."
    usage: "/customitem help"
    aliases: [customitem, ci]